services:
  sweet-crush:
    build: .
    container_name: sweet-crush-game
    ports:
      - "3099:3099"
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=3099
    labels:
      - "com.sweetcrush.description=Sweet Crush - Candy Match Game"
      - "com.sweetcrush.version=1.0"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3099"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 